[package]
name = "scop"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "scop"
path = "src/main.rs"

[dependencies]
# Window & event management — allowed by subject
sdl2 = "0.36"

# OpenGL function loader
gl = "0.14"

# Image loading for texture pixels only
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }

[features]
# Used in Dockerfile: statically compiles SDL2, avoids system dependency
bundled = ["sdl2/bundled"]